import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BAG, BAG_COLORS, BOARD } from '../src/core/constants.js';
import { LED_BOARD, SOUNDS } from '../src/presentation/effects.js';

/** The board look, LED behaviour and sound catalog as one JSON file for the Unity client. */
export function boardSpec(): string {
  return (
    JSON.stringify(
      {
        _comment: 'Generated by `npm run board` from server/src. Do not edit by hand.',
        boardIn: BOARD,
        bagIn: BAG,
        bagColors: BAG_COLORS,
        led: LED_BOARD,
        sounds: SOUNDS,
        logo: {
          files: {
            cyan: 'assets/logo/iplay-mark-cyan.png',
            white: 'assets/logo/iplay-mark-white.png',
            black: 'assets/logo/iplay-mark-black.png',
          },
          widthOnBagIn: 3.4,
        },
      },
      null,
      2,
    ) + '\n'
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = resolve(dirname(fileURLToPath(import.meta.url)), '../../assets/board/led-board.json');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, boardSpec());
  console.log('wrote assets/board/led-board.json');
}
